### ISSUE TITLE
Downloading Clone

### ISSUE THREAD

**Issue by IndieDiva** [NatronGitHub/natron-python-scripting#14]
Just a heads up, in the: 

"_**Installation**
The scripts can be installed by simply cloning the github repository, or download it as a ZIP file, by clicking on the top-right green button 'Clone or download'._" 

section, the graphic that should take you to the Clone or Download literally takes you to the image (link below)

https://github.com/NatronGitHub/natron-python-scripting/blob/master/Resources/download_button.png

:)

~Jackie

**Comment by rodlie** [comment]
Thanks for the heads up, added a link to the zip file instead of the image.
