### ISSUE TITLE
Crashes natron 2.5 on Mac Pro (OSX 12.7.2)

### ISSUE THREAD

**Issue by JamesBotterill** [NatronGitHub/natron-python-scripting#15]
I following instructions and when attempting to launch I get an error message. 

no further details provided

**Comment by rodlie** [comment]
> an error message

yes, and ...?

**Comment by JamesBotterill** [comment]
As I'm unable to get more information out of the wonderful OSX, it's a pretty useless error I'm aware.

Not sure what further details I can provide at this point.

Also other people might have similar issues.

**Comment by rodlie** [comment]
Without an error message (or something) it's a bit hard to do anything, I currently don't have time to test this on a Mac.

*In general I would advise against installing "everything" from this repo (and the community plugins) and rather only install the stuff you (want to) use. Testing of community addons might not always be the best (it's mostly assumed that it works if nobody complains).*
