### ISSUE TITLE
Python 3 and qtpy Translation

### ISSUE THREAD

**Issue by cgvirus** [NatronGitHub/natron-python-scripting#7]
Reference:
https://github.com/NatronGitHub/Natron/issues/695
https://github.com/NatronGitHub/Natron/issues/701

**Comment by cgvirus** [comment]
Working on it

**Comment by cgvirus** [comment]
qtpy linking is currently broken in Ntaron 2.5.0 Alpha in Linux. Waiting for a proper patch.

**Comment by cgvirus** [comment]
Py3 and qtpy translation is done.
https://github.com/NatronGitHub/natron-python-scripting/tree/py3-qtpy

Although Natron 2.5 qtpy binding is not patched properly in the binary.
https://github.com/NatronGitHub/Natron/issues/701#issuecomment-1146837031

An exception handling is injected for testing.

**Comment by rodlie** [comment]
is ``py3-qtpy`` ok to merge for https://github.com/NatronGitHub/Natron/releases/tag/v2.5.0?

**Comment by cgvirus** [comment]
> is `py3-qtpy` ok to merge for https://github.com/NatronGitHub/Natron/releases/tag/v2.5.0?

Hi @rodlie seems like qtpy is loading in the script editor. I will test the scripts for further errors now. Thanks for the update.

**Comment by cgvirus** [comment]
@rodlie [`py3-qtpy`](https://github.com/NatronGitHub/natron-python-scripting/tree/py3-qtpy) is updated and working both in 2.4 and https://github.com/NatronGitHub/Natron/releases/tag/v2.5.0

Tested OS:
Linux Mint 21
Windows 10

Should be safe to merge now.
Thanks!

**Comment by rodlie** [comment]
Great 👍 Thanks for doing the work.

**Comment by cgvirus** [comment]
Merged
https://github.com/NatronGitHub/natron-python-scripting/pull/13
